# Site settings
title: the.hoffblog.com
# email: your-email@domain.com
description: > # The Hoff Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://the.hoffblog.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mhoffmann

# Build settings
markdown: kramdown

highlighter: pygments
